##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "Becoming Caltech: Building a Research Community"
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: "a quick prototype of an exhibit site using CollectionBuilder-GH."
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: '"Becoming Caltech: Building a Research Community, 1910–1930" was originally a physical exhibit installed in the Beckman Room of the Archives and Special Collections. Now available as a digital exhibit, it explores Caltech’s transformation in the 1910s and 1920s—from a manual arts school to an engineering college, and ultimately into a world-renowned research institute. Through historical documents, photographs, objects, and film, the exhibit traces this period of rapid change, organized into three thematic sections that illuminate the roots of Caltech’s scientific legacy.'
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Caltech Archives and Special Collections

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: demo-data

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Caltech Archives and Special Collections"
# organization-link: https://library.caltech.edu/archives/home
# organization-logo-banner: /assets/img/logo-caltech.svg
# organization-logo-nav: /assets/img/logo-caltech.svg

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed

custom-foot: /_includes/js/item-js.html
